services:
  growth-api:
    build:
      context: .
      args:
        - GITHUB_SHA=${GITHUB_SHA:-}
    image: digital-growth-charts-server:built
    volumes:
      - .:/app
    ports:
      - "8000:8000"
