#!/bin/bash -e

az acr login --name ${AZURE_REGISTRY_NAME}

# Tests (development build)
docker compose up -d
s/test
docker compose down

# Rebuild using live dependencies
docker compose build --build-arg BUILD_ENVIRONMENT=live

# Push to Azure
azure_tag="${AZURE_REGISTRY_NAME}.azurecr.io/digital-growth-charts-server:${GITHUB_SHA}"
docker tag digital-growth-charts-server:built ${azure_tag}
docker push ${azure_tag}