#!/bin/bash

# names the container as below
app="rcpch-dgc-server"

# usage: `s/docker-start`
# run the container
# will error if a container already exists
# `docker container rm rcpch-dgc-server` to remove container
# or use the `s/rebuild-docker` script

docker run -it -p 8000:8000 \
  --name=${app} \
  --volume $PWD:/app \
  ${app}
