#!/bin/bash

# names the container as below
app="rcpch-dgc-server"

# usage: `s/start-docker`
# run the container
# will error if a container already exists
# `docker container rm rcpch-dgc-server` to remove container
# or use the `s/rebuild-docker` script

docker run -it -p 5000:5000 \
  --name=${app} \
  --volume $PWD:/app \
  ${app}
