#!/bin/bash

# runs the API server in production mode
# using gunicorn to manage 4 uvicorn workers
# used by Azure on deploy command

gunicorn -w 4 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker main:app