
name: Run tests for all new pushes and PRs (when opened or edited)

on:
  push: 
  pull_request:
    types: [opened, edited]
    

jobs:
  run-pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test-requirements.txt

      - name: Run pytest
        run: |
          pytest -v --tb=line