name: Run Pytest on pushes to main branches or PRs to any branch

on:
  pull_request:
    branches:
      - "*"

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run PR check script
        run: s/pr-check
