name: Run Pytest on pushes to main branches or PRs to any branch

on:
  pull_request:
    branches:
      - "*"

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run PR check script
        run: s/pr-check
