name: Run Pytest on pushes to main branches or PRs to any branch

on:
  pull_request:
    branches:
      - "*"

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Run PR check script
        run: s/pr-check
